[project]
name = "tdd-banco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "locust>=2.43.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
